[2017-04-28 00:16:57] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/cars/edit/undefined": Method Not Allowed (Allow: GET) (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/cars/edit/undefined\": Method Not Allowed (Allow: GET) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-04-28 00:16:57] application.ERROR: No route found for "POST /api/v1/cars/edit/undefined": Method Not Allowed (Allow: GET) [] []
[2017-04-28 00:16:57] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-28 00:34:56] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"undefined\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-28 00:34:56] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" [] []
[2017-04-28 00:34:56] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'undefined') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-28 01:05:14] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/parts/edit/1": Method Not Allowed (Allow: GET) (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/parts/edit/1\": Method Not Allowed (Allow: GET) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-04-28 01:05:14] application.ERROR: No route found for "POST /api/v1/parts/edit/1": Method Not Allowed (Allow: GET) [] []
[2017-04-28 01:05:14] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-28 01:05:39] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/parts/edit/1": Method Not Allowed (Allow: GET) (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/parts/edit/1\": Method Not Allowed (Allow: GET) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-04-28 01:05:39] application.ERROR: No route found for "POST /api/v1/parts/edit/1": Method Not Allowed (Allow: GET) [] []
[2017-04-28 01:05:39] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-28 01:06:26] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:06:26] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:06:26] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:10:53] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:10:53] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:10:53] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:11:11] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:11:11] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:11:11] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:14:53] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:14:53] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:14:53] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:18:37] application.CRITICAL: InvalidArgumentException: The controller for URI "/api/v1/parts/" is not callable. Expected method "index" on class "MyApp\Controller\PartsController". Available methods: "edit", "show", "select", "insert", "delete". (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 90 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/v1/parts/\" is not callable. Expected method \"index\" on class \"MyApp\\Controller\\PartsController\". Available methods: \"edit\", \"show\", \"select\", \"insert\", \"delete\". at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:90)"} []
[2017-04-28 01:18:37] application.ERROR: The controller for URI "/api/v1/parts/" is not callable. Expected method "index" on class "MyApp\Controller\PartsController". Available methods: "edit", "show", "select", "insert", "delete". [] []
[2017-04-28 01:18:37] application.ERROR: #0 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #1 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #10 {main} [] []
[2017-04-28 01:21:49] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:21:49] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:21:49] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:24:07] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:24:07] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:24:07] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:24:55] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:24:55] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:24:55] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:25:45] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:25:45] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:25:45] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:26:46] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:26:46] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:26:46] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:27:05] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:27:05] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:27:05] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:27:57] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:27:57] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:27:57] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:28:49] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:28:49] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:28:49] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:29:21] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:29:21] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:29:21] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:29:59] application.CRITICAL: InvalidArgumentException: Class "MyApp\PartsController" does not exist. (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 179 {"exception":"[object] (InvalidArgumentException(code: 0): Class \"MyApp\\PartsController\" does not exist. at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:179)"} []
[2017-04-28 01:29:59] application.ERROR: Class "MyApp\PartsController" does not exist. [] []
[2017-04-28 01:29:59] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php(87): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('MyApp\\PartsCont...') #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #4 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #11 {main} [] []
[2017-04-28 01:44:36] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/parts/part/" (from "http://localhost:8000/") (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/parts/part/\" (from \"http://localhost:8000/\") at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/parts/part/\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-28 01:44:36] application.ERROR: No route found for "GET /api/v1/parts/part/" (from "http://localhost:8000/") [] []
[2017-04-28 01:44:36] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
