[2017-04-27 00:00:18] application.CRITICAL: LogicException: The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php line 171 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php:171)"} []
[2017-04-27 00:00:18] application.ERROR: The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? [] []
[2017-04-27 00:00:18] application.ERROR: #0 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #1 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #8 {main} [] []
[2017-04-27 00:06:48] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'DELETE FROM user WHERE parent_id = ?' with params ["1"]:  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "user" LINE 1: DELETE FROM user WHERE parent_id = $1                     ^ (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'DELETE FROM user WHERE parent_id = ?' with params [\"1\"]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"user\"\nLINE 1: DELETE FROM user WHERE parent_id = $1\n                    ^ at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 42601): SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"user\"\nLINE 1: DELETE FROM user WHERE parent_id = $1\n                    ^ at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42601): SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"user\"\nLINE 1: DELETE FROM user WHERE parent_id = $1\n                    ^ at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 00:06:48] application.ERROR: An exception occurred while executing 'DELETE FROM user WHERE parent_id = ?' with params ["1"]:  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "user" LINE 1: DELETE FROM user WHERE parent_id = $1                     ^ [] []
[2017-04-27 00:06:48] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM use...', Array) #2 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM use...', Array, Array) #3 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(71): Doctrine\DBAL\Connection->delete('user', Array) #4 [internal function]: MyApp\Controller\CarController->delete(Object(Silex\Application), '1') #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2017-04-27 21:29:53] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"undefined\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 21:29:53] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" [] []
[2017-04-27 21:29:53] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'undefined') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 21:30:07] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"undefined\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 21:30:07] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" [] []
[2017-04-27 21:30:07] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'undefined') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 22:33:30] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["[object Object]"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "[object Object]" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"[object Object]\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"[object Object]\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"[object Object]\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"[object Object]\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 22:33:30] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["[object Object]"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "[object Object]" [] []
[2017-04-27 22:33:30] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), '[object Object]') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 22:33:37] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["[object Object]"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "[object Object]" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"[object Object]\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"[object Object]\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"[object Object]\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"[object Object]\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 22:33:37] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["[object Object]"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "[object Object]" [] []
[2017-04-27 22:33:37] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), '[object Object]') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 22:34:06] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"undefined\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 22:34:06] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" [] []
[2017-04-27 22:34:06] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'undefined') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 22:34:09] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"undefined\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 22:34:09] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" [] []
[2017-04-27 22:34:09] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'undefined') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 22:34:20] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"undefined\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"undefined\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 22:34:20] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["undefined"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" [] []
[2017-04-27 22:34:20] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'undefined') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 23:02:18] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/parts" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/parts\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/parts\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-27 23:02:18] application.ERROR: No route found for "GET /api/v1/parts" [] []
[2017-04-27 23:02:18] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-27 23:04:00] application.CRITICAL: InvalidArgumentException: The controller for URI "/api/v1/parts/" is not callable. Expected method "index" on class "MyApp\Controller\PartsController". Available methods: "edit", "show", "insert", "delete". (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 90 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/v1/parts/\" is not callable. Expected method \"index\" on class \"MyApp\\Controller\\PartsController\". Available methods: \"edit\", \"show\", \"insert\", \"delete\". at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:90)"} []
[2017-04-27 23:04:00] application.ERROR: The controller for URI "/api/v1/parts/" is not callable. Expected method "index" on class "MyApp\Controller\PartsController". Available methods: "edit", "show", "insert", "delete". [] []
[2017-04-27 23:04:00] application.ERROR: #0 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #1 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #10 {main} [] []
[2017-04-27 23:04:15] application.CRITICAL: InvalidArgumentException: The controller for URI "/api/v1/parts/" is not callable. Expected method "index" on class "MyApp\Controller\PartsController". Available methods: "edit", "show", "insert", "delete". (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 90 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/api/v1/parts/\" is not callable. Expected method \"index\" on class \"MyApp\\Controller\\PartsController\". Available methods: \"edit\", \"show\", \"insert\", \"delete\". at /var/www/html/n2oti/vendor/symfony/http-kernel/Controller/ControllerResolver.php:90)"} []
[2017-04-27 23:04:15] application.ERROR: The controller for URI "/api/v1/parts/" is not callable. Expected method "index" on class "MyApp\Controller\PartsController". Available methods: "edit", "show", "insert", "delete". [] []
[2017-04-27 23:04:15] application.ERROR: #0 /var/www/html/n2oti/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(47): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #1 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #10 {main} [] []
[2017-04-27 23:05:02] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/parts/show/2" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/parts/show/2\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/parts/show/2\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-27 23:05:02] application.ERROR: No route found for "GET /api/v1/parts/show/2" [] []
[2017-04-27 23:05:02] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-27 23:05:04] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/parts/show/3" (uncaught exception) at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/parts/show/3\" at /var/www/html/n2oti/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/parts/show/3\". at /var/www/html/n2oti/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-04-27 23:05:04] application.ERROR: No route found for "GET /api/v1/parts/show/3" [] []
[2017-04-27 23:05:04] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/n2oti/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-04-27 23:52:59] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"new\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 23:52:59] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" [] []
[2017-04-27 23:52:59] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'new') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 23:53:28] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"new\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 23:53:28] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" [] []
[2017-04-27 23:53:28] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'new') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 23:53:29] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"new\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 23:53:29] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" [] []
[2017-04-27 23:53:29] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'new') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 23:53:30] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"new\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 23:53:30] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" [] []
[2017-04-27 23:53:30] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'new') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2017-04-27 23:53:32] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" (uncaught exception) at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params [\"new\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new\" at /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-04-27 23:53:32] application.ERROR: An exception occurred while executing 'SELECT * FROM public.car WHERE parent_id = ?' with params ["new"]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "new" [] []
[2017-04-27 23:53:32] application.ERROR: #0 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/n2oti/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM p...', Array) #2 /var/www/html/n2oti/src/MyApp/Controller/CarController.php(44): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM p...', Array) #3 [internal function]: MyApp\Controller\CarController->show(Object(Silex\Application), 'new') #4 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/n2oti/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/n2oti/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/n2oti/web/index.php(17): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
